name: "Change iOS configuration"
description: "Change iOS configuration on info.plist"
inputs:
  infoPlistPath:
    description: "Info plist path to override version"
    required: true
    default: "ios/AppName/Info.plist"
  newCFBundleURLSchemes:
    description: "new CFBundleURLSchemes value"
    required: true
    default: "com.googleusercontent.apps.XXX"
  oldCFBundleURLSchemes:
    description: "Current CFBundleURLSchemes value to be replace"
    required: true
    default: "com.googleusercontent.apps.XXX2"
  cleanNSExceptionDomains:
    description: "Flag to clean NSExceptionDomains configuration"
    required: true
    default: "true"
outputs:
  result: # id of output
    description: "Action Result"
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  color: 'blue'
  icon: 'anchor'
